### ISSUE TITLE
Three item bar

### ISSUE THREAD

**Issue by thuugom** [Gurky-Kronos/LockPort#2]
![2022-05-29](https://user-images.githubusercontent.com/96802249/170874017-420c9bcf-830d-41e8-8ff1-a498cec12330.png)
Hello,

I figured out how to move the three item bar, but how do I make it disappear until I need it and on my none warlock toons?

Thank you

**Comment by Gurky-Kronos** [comment]
I believe it's /lockport stone

**Comment by Gurky-Kronos** [comment]
Yep /lockport stone hides it.

elseif msg == "stone" then -- Stone Frame Toggle (/lockport stone)
		if LockPort_SoulFrame:IsVisible() then
			LockPort_SoulFrame:Hide()
		else
			LockPort_SoulFrame:Show()
		end
